# Site settings
baseurl = "http://tulusha.com" #without ending slash
languageCode = "en-us"
title = "Eugene Tulusha"
theme = "hugo-identity-theme"
# themesDir = "../.."

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXX-Y"

[params]
  
  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance
  
  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Eugene Tulusha"
    # Avatars can be written to images/avatars/
    avatar = "avatar.jpg"
    position = "iOS Lead Engineer"
    livesIn = "[Dnipro, Ukraine](#some-maps-url)"
    # scope = [
    #     "Creator of [Moviest iOS app](#)",
    #     "Blogger on [Medium](#)",
    #     "Lovely husband for [butiful wife](https://www.instagram.com/vinyarskaya_t/)"
    #   ]
    biography = """I have wide experience in software and applications development for Apple devices, especially for iPhones and iPads. During my professional career I developed different applications for iOS platform from mobile games and entertainment through multimedia to enterprise applications for traveling and social networks."""



  # Contact form settings
    
  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "tulusheg@gmail.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = false
    title = "Touch Me!"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting us."
    error = "Message could not be send. Please contact us at "

    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com/alokard"

  [[params.social]]
    title = "Facebook"
    icon = "fa-facebook"
    link = "http://fb.com/tulusha.zhenia"

  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://linkedin.com/in/eugenetulusha/"

  [[params.social]]
    title = "GitHub"
    icon = "fa-github"
    link = "https://github.com/alokard"
  
  [[params.social]]
    title = "Instagram"
    icon = "fa-instagram"
    link = "https://instagram.com/alokard"

  [[params.social]]
    title = "Medium"
    icon = "fa-medium"
    link = "#"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Eugene Tulusha"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"