languageCode = "en-us"
title = "Eugene Tulusha"
baseurl = "http://tulusha.com/"
theme = "vienna"
disqusShortname = "tulusha"
copyright = "Copyright &copy; 2016-2017"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "alokard"
    github = "alokard"
    linkedin = "eugenetulusha"
    facebook = "tulusha.zhenia"
    instagram = "alokard"
    # Disqus shortname
    disqus = "tulusha"
    # Google Analytics API key.
    # ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    # author = "Eugene Tulusha"
    # avatar = "/static/avatar.png"
    # contact = "Your contact link (ex. mailto:foo@example.com)"
    # bio = "In {CODE} we trust"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "In {CODE} we trust"
    # themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
